---
title: "Econometrics II: Assignment 2"
author: "Walter Verwer & Bas Machielsen"
date: \today
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if(Sys.info()["user"] == "bas"){ # Mijn Linux
    Sys.setenv(RETICULATE_PYTHON = "/home/bas/anaconda3/bin/python")
    library(reticulate)
    reticulate::use_python("/home/bas/anaconda3/bin/python")
    py_available(TRUE)
} else if(Sys.info()["user"] == "basmachielsen"){# Mijn Mac
    Sys.setenv(RETICULATE_PYTHON = "/usr/bin/python")
    library(reticulate)
    reticulate::use_python("/usr/bin/python")
    py_available(TRUE)
} else {
    Sys.setenv(RETICULATE_PYTHON = "C:\\Users\\walte\\anaconda3")
    library(reticulate)
    reticulate::use_python("C:\\Users\\walte\\anaconda3")
    py_available(TRUE) 
}

# Hier kunnen we zien of alles is goed gegaan 
py_config()
```

## Question 1

First use pooled OLS to check the impact of including and excluding ASVABC
on the estimate of α 1 . Present and explain the result.

```{python load packages}
import pandas as pd
import statsmodels.api as sm
from stargazer.stargazer import Stargazer
from IPython.core.display import HTML
import numpy as np
```


```{python}
earnings = pd.read_csv("~/Documents/git/econometrics2/assignment2/data/NLSY2000RC_V2.csv")

ivs = ['ASVABC','AGE', 'AGESQ','S','ETHBLACK','URBAN','REGNE','REGNC','REGW','REGS']

y = ['EARNINGS']

earnings = earnings.dropna()
```

```{python, results='asis'}
model_with = sm.OLS(endog=earnings[y], exog=sm.add_constant(earnings[ivs])).fit()

model_without = sm.OLS(endog=earnings[y], exog=sm.add_constant(earnings[ivs[1:]])).fit()

stargazer = Stargazer([model_with,  model_without])
stargazer.covariate_order(ivs)
stargazer.render_html()
```

The inclusion of the proxy ability decreases the estimate for the coefficient of schooling. Hence, given all other standard assumptions, ability and schooling are positively correlated, and the omission of a proxy for ability overestimates the impact of schooling.

## Question 2

Perform a pooled OLS analysis to obtain insight in the heterogeneity of returns to schooling by ethnicity. Present the results and comment on the outcomes: what are the conclusions based on this?

```{python, results='asis'}
# including a cross effect of schooling and ethnicity
earnings['BLACKxS'] = earnings['ETHBLACK'] * earnings['S']

ivs2 = ivs + ['BLACKxS']

est_ear_inter = sm.OLS(endog=earnings[y], exog = sm.add_constant(earnings[ivs2])).fit()

# estimating separate equations by ethnicity
earnings_noblack = earnings[earnings['ETHBLACK'] == 0]
earnings_black = earnings[earnings['ETHBLACK'] == 1]


est_ear_noblack = sm.OLS(endog=earnings_noblack[y],exog=sm.add_constant(earnings_noblack[ivs])).fit()

est_ear_black = sm.OLS(endog=earnings_black[y],exog=sm.add_constant(earnings_black[ivs])).fit()

stargazer = Stargazer([est_ear_inter, est_ear_noblack,  est_ear_black])
stargazer.covariate_order(['BLACKxS']+ivs)
stargazer.custom_columns(['Interaction','Not Black', 'Black'], [1,1,1])
stargazer.render_html()
```

We can see that the interaction effect is insignificant: that is to say, there is no significant different between blacks and non-black in the influence of schooling on earnings. When we split up the sample into blacks and non-black, we get a slightly different view: the point estimate for the effect of schooling seems to be slightly lower for black people than for non-black people. However, as seen in the pooled regression with interaction effect, the differential impact is not statistically significant. 

## Question 3

Perform the analysis for heterogenous schooling effects using the random effects model. Present the results and compare the outcomes with the pooled OLS results obtained before. Interpret the outcomes.

```{python}
from linearmodels import RandomEffects

earnings_indexed = earnings.set_index(['ID', 'TIME'])
#earnings['TIME'] = time

hoi = earnings_indexed[ivs]
dep = earnings_indexed[y]

re_model = RandomEffects(dep, hoi).fit()

print(re_model)

```

The point estimate for schooling is now close to the point estimate for schooling in the pooled OLS regression including the proxy for ability. Hence, the random effects estimator looks a lot like the pooled estimator, indicating that the contribution from the within group estimator is marginal. This can also be observed when looking at the decomposition of the explained variance: the between R-squared is larger than the within R-squared, indicating the model does a better job explaining the changes between individuals rather than individuals over time. 


