---
title: "Assignment 4"
author: "Bas Machielsen & Walter Verwer"
date: \today
output:
  pdf_document:
    includes:
      in_header: "preamble.tex"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Register an inline hook (set rounding to 3 digitis):
# knitr::knit_hooks$set(inline = function(x) {
#   x <- sprintf("%1.3f", x)
#   paste(x, collapse = ", ")
# })

library(stargazer)
library(tidyverse)
library(haven)
library(knitr)
library(lmtest)
library(sandwich)

# Import Stata dataset
flu <- haven::read_dta("./data/FluData.dta")

```

## Problem 1: Judges and Prison Sentences
__(i) Use the Wald estimator to compute the causal effect of a prison sentence on the probability of being arrested later.__

The Wald estimator is defined as follows:

\[\frac{E[Y|Z=1] - E[Y|Z=0]}{E[D|Z=1] - E[D|Z=0]}\]

In our case, $Y$ is the future arrest, $Z=1$ if the judge is Jones, and it is equal to zero if it is Smith, and $D=1$ if the individual went to prison, and zero otherwise. Filling in the formula with the numbers given, results in following:

\[ \frac{(70\% \cdot 40\% + 30\% \cdot 60\%)- (40\% \cdot 20\% + 60\% \cdot 50\%)}{70\% - 40\%} = 0.27 \]

__(ii) What is the interpretation of the estimated effect? And for which fraction of the population does this causal effect hold?__

The interpretation of this is that sending an individual to prison results in a 27% higher probability that the individual has to go to prison again. The fraction for which this causal effect hold is the people that comply. That is, the fraction of the people that go to prison if they are assigned to Jones and do not go to prison if they are assigned to Smith plus the fraction of people that do not go to prison under Jones, but go to prison under Smith. This fraction is equal to $0.7 \cdot 0.6 +0.4 \cdot 0.3 = 0.54$.

__(iii) Explain what an always taker is in this setting and which fraction of the population are always takers?__
An always taker is someone who always takes up treatment. In this situation an always taker is someone who will always go to prison. This would be someone who comitted a very bad crime, such that both judges sentence the individual to prison, think about someone who comitted a murder. This fraction equals $0.7 \cdot 0.4 = 0.28$.


## Problem 2: Eating and Drinking
__(i) Perform a power calculation for the number of students that the teacher should include in the field experiment.__

Compute the power as follows.

\[MDE = (t_{1-\alpha/2} -t_{1-q}) \sqrt{\frac{1}{p(1-p)}}\sqrt{\frac{\sigma^2}{n}}\]

Filling in the values given, results in the following.

\[0.1 = (1.96 + 0.524) \sqrt{\frac{1}{0.25}}\sqrt{\frac{0.25}{n}} \implies n\approx617\]

In this calculation, the variance follows from a standard Bernoulli variance calculation. In our case $p=0.5$, which implies that the variance is 0.25.

__(ii)The teacher assumes that 20% of the students randomized in the treatment group will actually have breakfast. How does this change the number of students required to participate in the field experiment?__

We take the formula from the previous question and change it accordingly. This results the following formula.

\[MDE = (t_{1-\alpha/2} -t_{1-q}) \sqrt{\frac{1}{p(1-p)}}\sqrt{\frac{\sigma^2}{n}}\frac{1}{r_t-t_c}\]

Filling in the values again gives us the following.

\[0.1 = (1.96 + 0.524) \sqrt{\frac{1}{0.25}}\sqrt{\frac{0.25}{n}}\frac{1}{0.8-0} \implies n\approx964\]

Concluding, we observe that the partial compliance increases the number of observations needed.


## Problem 3: Flu shots for young children
__(i) Compute for the children assigned to the control group the variance in u incidence. If the researcher aims at reducing u incidence by 0.05, how many children should participate in the randomized experiment.__















